#!/usr/bin/env bash
# scaffold-project.sh — Generates a new project directory from templates and a config file
#
# Usage: ./scripts/scaffold-project.sh <config-file.json>
#
# The config file is generated by the Orchestrator during the interactive Q&A.
# This script reads it and builds the full project directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATES_DIR="$ROOT_DIR/templates"
PROJECTS_DIR="$ROOT_DIR/projects"

# --- Input validation ---
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <config-file.json>"
  exit 1
fi

CONFIG_FILE="$1"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Error: Config file not found: $CONFIG_FILE"
  exit 1
fi

# --- Parse config (requires jq) ---
if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install with: brew install jq (macOS) or apt install jq (Linux)"
  exit 1
fi

PROJECT_NAME=$(jq -r '.project.name' "$CONFIG_FILE")
PROJECT_TYPE=$(jq -r '.project.type' "$CONFIG_FILE")
PROJECT_DESC=$(jq -r '.project.description' "$CONFIG_FILE")
PROJECT_GOAL=$(jq -r '.project.goal' "$CONFIG_FILE")
CREATED_DATE=$(date -u +"%Y-%m-%d")

# Validate project name
if [[ -z "$PROJECT_NAME" || "$PROJECT_NAME" == "null" ]]; then
  echo "Error: project.name is required in config"
  exit 1
fi

PROJECT_DIR="$PROJECTS_DIR/$PROJECT_NAME"

if [[ -d "$PROJECT_DIR" ]]; then
  echo "Error: Project directory already exists: $PROJECT_DIR"
  exit 1
fi

echo "=== Scaffolding project: $PROJECT_NAME ==="
echo "  Type: $PROJECT_TYPE"
echo "  Description: $PROJECT_DESC"
echo ""

# --- Create directory structure ---
mkdir -p "$PROJECT_DIR/.claude/agents"
mkdir -p "$PROJECT_DIR/.claude/skills"
mkdir -p "$PROJECT_DIR/docs"
mkdir -p "$PROJECT_DIR/src"

# --- Copy .claude/settings.json ---
cp "$TEMPLATES_DIR/project/.claude/settings.json" "$PROJECT_DIR/.claude/settings.json"

# --- Copy Team Lead (always) ---
cp "$TEMPLATES_DIR/agents/team-lead.md" "$PROJECT_DIR/.claude/agents/team-lead.md"
echo "  ✓ Agent: team-lead"

# --- Copy selected agents ---
AGENTS=$(jq -r '.agents[]' "$CONFIG_FILE" 2>/dev/null || echo "")
AGENT_LIST_MD=""
AGENT_ENTRIES_MD=""
AGENT_NAMES="team-lead"

for AGENT in $AGENTS; do
  if [[ "$AGENT" == "team-lead" ]]; then
    continue
  fi
  
  AGENT_FILE="$TEMPLATES_DIR/agents/${AGENT}-agent.md"
  # Try without -agent suffix too
  if [[ ! -f "$AGENT_FILE" ]]; then
    AGENT_FILE="$TEMPLATES_DIR/agents/${AGENT}.md"
  fi
  
  if [[ -f "$AGENT_FILE" ]]; then
    cp "$AGENT_FILE" "$PROJECT_DIR/.claude/agents/"
    echo "  ✓ Agent: $AGENT"
    AGENT_NAMES="$AGENT_NAMES, $AGENT"
    
    # Extract description from frontmatter
    AGENT_DESC=$(sed -n '/^description:/,/^[a-z]/{ /^description:/{ s/^description: *>* *//; p; }; /^  /p; }' "$AGENT_FILE" | head -3 | tr '\n' ' ' | sed 's/  */ /g')
    AGENT_LIST_MD="$AGENT_LIST_MD\n- **${AGENT^}**: $AGENT_DESC"
    AGENT_ENTRIES_MD="$AGENT_ENTRIES_MD\n### ${AGENT^}\n- **File**: \`.claude/agents/$(basename "$AGENT_FILE")\`\n- **Model**: sonnet\n"
  else
    echo "  ⚠ Agent template not found: $AGENT (skipped)"
  fi
done

# --- Build skills list ---
SKILLS=$(jq -r '.skills[]' "$CONFIG_FILE" 2>/dev/null || echo "")
SKILL_NAMES=""
SKILL_ENTRIES_MD=""

for SKILL in $SKILLS; do
  SKILL_NAMES="${SKILL_NAMES:+$SKILL_NAMES, }$SKILL"
  SKILL_ENTRIES_MD="$SKILL_ENTRIES_MD\n### $SKILL\n- **Source**: See parent SKILLS.md for details\n"
  
  # Copy skill directory if it exists in templates
  if [[ -d "$TEMPLATES_DIR/skills/$SKILL" ]]; then
    cp -r "$TEMPLATES_DIR/skills/$SKILL" "$PROJECT_DIR/.claude/skills/"
    echo "  ✓ Skill: $SKILL (copied)"
  else
    echo "  ✓ Skill: $SKILL (reference only — uses built-in or parent)"
  fi
done

# --- Get project-specific rules ---
PROJECT_RULES=$(jq -r '.rules // "No project-specific rules yet. Add them as needed."' "$CONFIG_FILE")

# --- Get project context ---
PROJECT_CONTEXT=$(jq -r '.context // "No additional context provided."' "$CONFIG_FILE")

# --- Generate CLAUDE.md ---
sed \
  -e "s|{PROJECT_NAME}|$PROJECT_NAME|g" \
  -e "s|{PROJECT_DESCRIPTION}|$PROJECT_DESC|g" \
  -e "s|{PROJECT_TYPE}|$PROJECT_TYPE|g" \
  -e "s|{PROJECT_GOAL}|$PROJECT_GOAL|g" \
  -e "s|{CREATED_DATE}|$CREATED_DATE|g" \
  -e "s|{PROJECT_CONTEXT}|$PROJECT_CONTEXT|g" \
  "$TEMPLATES_DIR/project/CLAUDE.md" > "$PROJECT_DIR/CLAUDE.md"

# Replace multi-line placeholders
if [[ -n "$AGENT_LIST_MD" ]]; then
  python3 -c "
import sys
content = open('$PROJECT_DIR/CLAUDE.md').read()
content = content.replace('{AGENT_LIST}', '''$(echo -e "$AGENT_LIST_MD")''')
content = content.replace('{SKILLS_LIST}', '''$(echo -e "$SKILL_ENTRIES_MD")''')
open('$PROJECT_DIR/CLAUDE.md', 'w').write(content)
" 2>/dev/null || true
fi

echo "  ✓ CLAUDE.md"

# --- Generate AGENTS.md ---
sed \
  -e "s|{PROJECT_NAME}|$PROJECT_NAME|g" \
  "$TEMPLATES_DIR/project/AGENTS.md" > "$PROJECT_DIR/AGENTS.md"

python3 -c "
content = open('$PROJECT_DIR/AGENTS.md').read()
content = content.replace('{AGENT_ENTRIES}', '''$(echo -e "$AGENT_ENTRIES_MD")''')
open('$PROJECT_DIR/AGENTS.md', 'w').write(content)
" 2>/dev/null || true

echo "  ✓ AGENTS.md"

# --- Generate SKILLS.md ---
sed \
  -e "s|{PROJECT_NAME}|$PROJECT_NAME|g" \
  "$TEMPLATES_DIR/project/SKILLS.md" > "$PROJECT_DIR/SKILLS.md"

python3 -c "
content = open('$PROJECT_DIR/SKILLS.md').read()
content = content.replace('{SKILL_ENTRIES}', '''$(echo -e "$SKILL_ENTRIES_MD")''')
open('$PROJECT_DIR/SKILLS.md', 'w').write(content)
" 2>/dev/null || true

echo "  ✓ SKILLS.md"

# --- Generate RULES.md ---
sed \
  -e "s|{PROJECT_NAME}|$PROJECT_NAME|g" \
  -e "s|{PROJECT_RULES}|$PROJECT_RULES|g" \
  "$TEMPLATES_DIR/project/RULES.md" > "$PROJECT_DIR/RULES.md"
echo "  ✓ RULES.md"

# --- Generate CHANGELOG.md ---
sed \
  -e "s|{PROJECT_NAME}|$PROJECT_NAME|g" \
  -e "s|{CREATED_DATE}|$CREATED_DATE|g" \
  -e "s|{PROJECT_TYPE}|$PROJECT_TYPE|g" \
  -e "s|{PROJECT_GOAL}|$PROJECT_GOAL|g" \
  -e "s|{AGENT_NAMES}|$AGENT_NAMES|g" \
  -e "s|{SKILL_NAMES}|$SKILL_NAMES|g" \
  "$TEMPLATES_DIR/project/CHANGELOG.md" > "$PROJECT_DIR/CHANGELOG.md"
echo "  ✓ CHANGELOG.md"

# --- Generate project settings.json ---
cat > "$PROJECT_DIR/settings.json" << EOF
{
  "project": {
    "name": "$PROJECT_NAME",
    "type": "$PROJECT_TYPE",
    "description": "$PROJECT_DESC",
    "goal": "$PROJECT_GOAL",
    "created": "$CREATED_DATE",
    "status": "active"
  },
  "agents": $(jq '.agents // ["team-lead"]' "$CONFIG_FILE"),
  "skills": $(jq '.skills // []' "$CONFIG_FILE")
}
EOF
echo "  ✓ settings.json"

echo ""
echo "=== Project scaffolded successfully ==="
echo "  Location: $PROJECT_DIR"
echo ""
echo "  To start working:"
echo "    cd $PROJECT_DIR"
echo "    claude"
echo ""
echo "  The Team Lead agent is ready and will coordinate all work."
