#!/bin/bash
# =============================================================================
# weekly-entity-scan.sh — Cross-project entity map generator
# Runs at 10:00 PM Sunday Muscat time (18:00 UTC Sunday) via crontab
#
# Scans all projects for mentions of people, companies, and systems.
# Builds/updates ENTITIES.md at the orchestrator root.
# Used by morning digest and nightly maintenance for enriched context.
# =============================================================================

ORCHESTRATOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAUDE="${CLAUDE_CMD:-$(command -v claude 2>/dev/null || echo 'claude')}"
ENTITIES_FILE="$ORCHESTRATOR_DIR/ENTITIES.md"
LOG_FILE="$ORCHESTRATOR_DIR/reports/cron-run.log"
WORKFLOW_LOG="$ORCHESTRATOR_DIR/reports/workflow-log.md"

mkdir -p "$ORCHESTRATOR_DIR/reports"

echo "" >> "$LOG_FILE"
echo "========================================" >> "$LOG_FILE"
echo "Weekly entity scan started: $(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG_FILE"
echo "========================================" >> "$LOG_FILE"

echo "[$(date '+%H:%M:%S')] Scanning all projects for entities..." >> "$LOG_FILE"

"$CLAUDE" --print \
  --allowedTools "Read,Write,Edit,Glob,Grep" \
  --permission-mode bypassPermissions \
  --max-turns 40 \
  "You are the Orchestrator running the weekly cross-project entity scan.

DATE: $(date '+%Y-%m-%d, %A')
ORCHESTRATOR: $ORCHESTRATOR_DIR

---

## Your Task

Scan all projects under \`projects/\` and extract every meaningful entity across the portfolio. The goal is to build a shared entity map that gives cross-project context — so that when the morning digest or nightly report mentions 'Ahmad' or 'Salesforce', there's a shared understanding of who/what that is and which projects they touch.

---

## Step 1: Gather Raw Data

For each project in \`projects/\`:
1. Read \`CLAUDE.md\` and \`settings.json\` to understand what the project is about
2. Read \`AGENTS.md\` and any project notes for entity mentions
3. Read any log files, contact lists, or data files that might contain entity names
4. Look for recurring names (people, companies, systems, tools) mentioned across files

Focus on:
- **People**: named individuals, roles with names attached (\"Ahmad - CEO\", \"Sarah from procurement\")
- **Companies/Organisations**: clients, vendors, partners, government bodies
- **Systems/Tools**: specific software, databases, APIs, external services referenced by name
- **Locations**: offices, cities, addresses that recur in a business context

---

## Step 2: Deduplicate and Categorise

Group all found entities by type. Merge duplicates (\"Ahmad\", \"Ahmad Al-Rashidi\", \"Mr. Ahmad\" → one entry).

---

## Step 3: Write ENTITIES.md

Write the full entity map to: $ENTITIES_FILE

Use this format:

\`\`\`markdown
# Cross-Project Entity Map
**Last updated:** $(date '+%Y-%m-%d') | **Scan covers:** {N} projects

> Auto-generated by weekly-entity-scan.sh. Edit manually to add notes or correct entries. Will be regenerated weekly (Sunday nights).

---

## 👤 People

| Name | Role / Notes | Projects |
|------|-------------|---------|
| Name | Role or context | project-a, project-b |

---

## 🏢 Companies & Organisations

| Name | Type | Notes | Projects |
|------|------|-------|---------|
| Name | Client / Vendor / Partner | Context | project-a |

---

## 🖥️ Systems & Tools

| Name | Type | Notes | Projects |
|------|------|-------|---------|
| Name | CRM / API / Database | Context | project-a |

---

## 📍 Locations

| Name | Type | Notes | Projects |
|------|------|-------|---------|

---

*To add an entry manually: edit this file. The weekly scan merges new findings but preserves manual notes.*
\`\`\`

---

## Step 4: Log the scan

Append a summary entry to: $WORKFLOW_LOG

Header: \`## Entity Scan — $(date '+%Y-%m-%d')\`
Include: how many entities found per type, which projects contributed.

Then print a one-line summary to stdout.
" 2>&1 | tee -a "$LOG_FILE"

echo "Weekly entity scan finished: $(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG_FILE"
